"""
Optional rule-based heuristics for quick checks.
"""
import re


def contains_model_signature(text: str) -> bool:
    patterns = [r"as an AI language model", r"I am an AI", r"generated by"]
    for p in patterns:
        if re.search(p, text, re.IGNORECASE):
            return True
    return False


def over_perfect_grammar(text: str) -> bool:
    # Placeholder: simple heuristic — extremely long sentences count
    sentences = [s for s in text.split('.') if s.strip()]
    long_sents = [s for s in sentences if len(s.split()) > 60]
    return len(long_sents) > 0


def rule_based_score(text: str) -> dict:
    return {
        'signature_present': contains_model_signature(text),
        'over_perfect_grammar': over_perfect_grammar(text)
    }
